# These are supported funding model platforms

github: Syahriz-Bot
patreon: # Replace with a single Patreon username
open_collective: Whatsapp-Bot
ko_fi: # Replace with a single Ko-fi username
tidelift: PC
community_bridge: SYAHRIZBOT
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: Hariz
custom:  https://instagram.com/_.riz.s
